######################################################################
# Automatically generated by qmake (2.01a) Sat May 17 11:38:47 2008
######################################################################

TEMPLATE = subdirs
SUBDIRS = sub_src sub_examples

sub_src.subdir = src
sub_examples.subdir = examples
